name: Java 17 gradle build
description: Java 17 gradle build
inputs:
  project:
    description: Project name
    required: true
  github-token:
    description: Checkout github token
    required: true
  context:
    description: Build Context, aka workdir
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 17
    uses: actions/setup-java@v3.3.0
    with:
      java-version: '17'
      distribution: adopt
      cache: gradle
      check-latest: true
  - name: Gradle Wrapper Validation
    uses: gradle/wrapper-validation-action@v1.0.4
  - name: Gradle Build Action
    uses: gradle/gradle-build-action@v2.2.0
  - name: Execute Gradle build
    run: ./gradlew build